services:
  postgres:
    restart: unless-stopped
    image: postgres:10
    ports:
      - "5555:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./init-scripts:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=appointments"
    networks:
      - shared-net

  ktor-server:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=appointments
      - DB_USER=postgres
      - DB_PASSWORD=password
      - KAFKA_BROKER=kafka:9092
    command: [ "java", "-jar", "/app/ktor-server.jar" ]
    restart: unless-stopped
    networks:
      - shared-net

volumes:
  postgres-data:

networks:
  shared-net:
    external: true
    name: kafka-network