ktor:
    application:
        modules:
            - cz.mokripat.appointment.ApplicationKt.module
    deployment:
        port: 8089


database:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5555/appointments"
    user: "postgres"
    password: "password"
    maxConnections: 10
