openapi: 3.0.3
info:
  title: Appointment Service API
  description: API for handling appointment bookings, updates, cancellations, and validating doctor availability
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /appointments:
    get:
      summary: Get all appointments
      description: Retrieves a list of all appointments
      responses:
        '200':
          description: A list of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'

  /appointment/{id}:
    get:
      summary: Get a specific appointment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Appointment details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '404':
          description: Appointment not found

    put:
      summary: Update an appointment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '200':
          description: Appointment updated
        '404':
          description: Appointment not found

    delete:
      summary: Cancel an appointment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Appointment cancelled
        '404':
          description: Appointment not found

  /appointment:
    post:
      summary: Book a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Appointment created

components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: string
        doctorId:
          type: string
        patientId:
          type: string
        from:
          type: string
          format: date-time
        to:
          type: string
          format: date-time
        note:
          type: string
        status:
          type: string
          enum: ["booked", "cancelled", "completed"]
